#ifndef __LINUX_PCI_IDS_H__
#define __LINUX_PCI_IDS_H__

#define PCI_VENDOR_ID_INTEL		0x8086

#define PCI_CLASS_NOT_DEFINED		0x0000

#define PCI_CLASS_STORAGE_IDE		0x0101

#define PCI_CLASS_BRIDGE_HOST		0x0600

#define PCI_CLASS_BRIDGE_PCI		0x0604

#define PCI_CLASS_BRIDGE_CARDBUS	0x0607

#endif /* ! __LINUX_PCI_IDS_H__ */
